Pre-process:

1) Solve Missings

    - doesn't exist vs not recorded
    
    - how many?
    
    - remove or impute 
    
2) Remove outliers

    - noise vs different
    
    - how many?
    
    - remove or impute

3) Remove columns or Dimension reduction

    - remove not relevent columns or duplicated topics
    
    - dimension reduction
   
           
4) Add columns
                    
    - combine features like ratios
    
    - polynomial
    

5) Transforming
    
    - log, sqrt, ...
    
    - standard scaler, min max scaler
        
    - change str to numeric: Ordinal encoding or One-hot encoding

In [1]:
from pandas import DataFrame


df = DataFrame(data=[[2018, 1.5],
                     [2019, 1.7],
                     [2020, 1.9]],
               index=['row1', 'row2', 'row3'],
               columns=['year', 'some_value'])

In [2]:
df.loc['row1']

year          2018.0
some_value       1.5
Name: row1, dtype: float64

In [3]:
df.iloc[0]

year          2018.0
some_value       1.5
Name: row1, dtype: float64

In [4]:
df['some_value']

row1    1.5
row2    1.7
row3    1.9
Name: some_value, dtype: float64

In [5]:
df.iloc[:,1]

row1    1.5
row2    1.7
row3    1.9
Name: some_value, dtype: float64

In [6]:
df.columns

Index(['year', 'some_value'], dtype='object')

In [7]:
df.values

array([[2.018e+03, 1.500e+00],
       [2.019e+03, 1.700e+00],
       [2.020e+03, 1.900e+00]])

In [8]:
df.year.value_counts()

2018    1
2019    1
2020    1
Name: year, dtype: int64

In [24]:
# df.drop(0, inplace=True)
# df.drop('year', axis=1, inplace=True)

In [9]:
df[0:3]

year  some_value
row1  2018         1.5
row2  2019         1.7
row3  2020         1.9

In [10]:
df[df.year > 2019]

year  some_value
row3  2020         1.9

In [11]:
df[(df.year < 2019) & (df['some_value'] == 1.5)]

year  some_value
row1  2018         1.5

In [12]:
df[['some_value','year']]

some_value  year
row1         1.5  2018
row2         1.7  2019
row3         1.9  2020

In [22]:
df.loc[df['year'] > 2019, ['some_value','year']]

some_value  year
row3         1.9  2020

In [13]:
df[df['year'].isin([2019, 2020])]

year  some_value
row2  2019         1.7
row3  2020         1.9

In [15]:
df.year.replace({2019: 19, 2020: 20, 2018: 18}, inplace=True)
df

year  some_value
row1    18         1.5
row2    19         1.7
row3    20         1.9

In [16]:
df.iat[0, 1] = 1
df

year  some_value
row1    18         1.0
row2    19         1.7
row3    20         1.9

In [20]:
df.at['row1', 'year'] = 1
df

year  some_value
row1     1         1.0
row2    19         1.7
row3    20         1.9

In [21]:
df.mean()

year          13.333333
some_value     1.533333
dtype: float64

In [22]:
df.sort_values(by='year')

year  some_value
row1     1         1.0
row2    19         1.7
row3    20         1.9

In [23]:
df.head()

year  some_value
row1     1         1.0
row2    19         1.7
row3    20         1.9

In [26]:
df.tail(1)

year  some_value
row3    20         1.9

In [27]:
from pandas import concat

df1 = DataFrame([['a', 1],
                ['b', 2]])
df2 = DataFrame([['c', 1],
                ['d', 2]])

In [28]:
concat([df1,df2])

0  1
0  a  1
1  b  2
0  c  1
1  d  2

In [29]:
df3 = DataFrame([[True], [False]])
concat([df1,df3], axis=1)

0  1      0
0  a  1   True
1  b  2  False

In [30]:
# from pandas import read_csv
# df = read_csv('file.csv')

In [31]:
from pandas import DataFrame, get_dummies

df = DataFrame([['Teh', 2],
                ['Qom', 4],
                ['Teh', 6],
                ['Tab', 6],], 
               columns=['city', 'some_value'])

one_hot = get_dummies(df['city'])
df = df.drop('city', axis=1)
df = df.join(one_hot)
df

some_value  Qom  Tab  Teh
0           2    0    0    1
1           4    1    0    0
2           6    0    0    1
3           6    0    1    0

In [32]:
df.to_numpy()

array([[2, 0, 0, 1],
       [4, 1, 0, 0],
       [6, 0, 0, 1],
       [6, 0, 1, 0]])

In [33]:
df.describe()

some_value   Qom   Tab      Teh
count    4.000000  4.00  4.00  4.00000
mean     4.500000  0.25  0.25  0.50000
std      1.914854  0.50  0.50  0.57735
min      2.000000  0.00  0.00  0.00000
25%      3.500000  0.00  0.00  0.00000
50%      5.000000  0.00  0.00  0.50000
75%      6.000000  0.25  0.25  1.00000
max      6.000000  1.00  1.00  1.00000

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   some_value  4 non-null      int64
 1   Qom         4 non-null      uint8
 2   Tab         4 non-null      uint8
 3   Teh         4 non-null      uint8
dtypes: int64(1), uint8(3)
memory usage: 172.0 bytes


In [36]:
for index, row in df.iterrows():
    print(row)
    print('---------')

some_value    2
Qom           0
Tab           0
Teh           1
Name: 0, dtype: int64
---------
some_value    4
Qom           1
Tab           0
Teh           0
Name: 1, dtype: int64
---------
some_value    6
Qom           0
Tab           0
Teh           1
Name: 2, dtype: int64
---------
some_value    6
Qom           0
Tab           1
Teh           0
Name: 3, dtype: int64
---------


In [37]:
df = DataFrame([[None, 2],
                ['Tab', 4],
                ['Teh', None]], 
               columns=['city', 'some_value'])

In [38]:
df.isna().sum()

city          1
some_value    1
dtype: int64

In [39]:
df.dropna(how='any', inplace=True)
df

city  some_value
1  Tab         4.0

In [40]:
df[df.notnull()]

city  some_value
1  Tab         4.0

In [41]:
df = DataFrame([['Teh', 2],
                ['Tab', 4],
                ['Teh', 6]], 
               columns=['city', 'some_value'])
df.groupby('city').mean()

some_value
city            
Tab          4.0
Teh          4.0

In [42]:
from sklearn.preprocessing import scale, minmax_scale
from math import nan
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [43]:
X_train = [[1, 2], [3, 4]]
scale(X_train) # x - avg / std -> avg wil be 0

array([[-1., -1.],
       [ 1.,  1.]])

In [44]:
minmax_scale(X_train)

array([[0., 0.],
       [1., 1.]])

In [46]:
x_train = [[1, 2], [3, 6], [4, 8], [nan, 3], [7, nan]]
x_test = [[nan, 2], [6, nan], [nan, 6]]
imp = IterativeImputer(max_iter=10, missing_values=nan)
imp.fit(x_train)
print(imp.transform(x_test).round(2))

[[ 1.  2.]
 [ 6. 12.]
 [ 3.  6.]]


In [48]:
from pandas import DataFrame
df = DataFrame([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
f = lambda x: (x - x.min()) / (x.max() - x.min())
df.apply(f) # column-wise to all columns

0    1    2
0  0.0  0.0  0.0
1  0.5  0.5  0.5
2  1.0  1.0  1.0

In [49]:
df.iloc[:,0].map(lambda x: 1 / x) # element-wise to one column

0    1.000000
1    0.250000
2    0.142857
Name: 0, dtype: float64

In [50]:
df.applymap(lambda x: 1 / x) # element-wise to all cells

0      1         2
0  1.000000  0.500  0.333333
1  0.250000  0.200  0.166667
2  0.142857  0.125  0.111111

In [51]:
df.where(df > 2, -1)
# where(cond, other=nan, inplace=False) 
# Replace values where the condition is False.

0  1  2
0 -1 -1  3
1  4  5  6
2  7  8  9